// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projekt___Avancerad_.NET.Data;

#nullable disable

namespace Project.Advanced.Net.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240515072237_Initial Creation")]
    partial class InitialCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectModels.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("AppointmentId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            AppointmentId = 1,
                            CompanyId = 1,
                            CustomerId = 1,
                            Time = new DateTime(2024, 5, 15, 9, 22, 37, 51, DateTimeKind.Local).AddTicks(4092)
                        },
                        new
                        {
                            AppointmentId = 2,
                            CompanyId = 1,
                            CustomerId = 2,
                            Time = new DateTime(2024, 5, 25, 9, 22, 37, 51, DateTimeKind.Local).AddTicks(4148)
                        },
                        new
                        {
                            AppointmentId = 3,
                            CompanyId = 2,
                            CustomerId = 3,
                            Time = new DateTime(2024, 6, 4, 9, 22, 37, 51, DateTimeKind.Local).AddTicks(4162)
                        },
                        new
                        {
                            AppointmentId = 4,
                            CompanyId = 3,
                            CustomerId = 4,
                            Time = new DateTime(2024, 6, 14, 9, 22, 37, 51, DateTimeKind.Local).AddTicks(4173)
                        },
                        new
                        {
                            AppointmentId = 5,
                            CompanyId = 4,
                            CustomerId = 1,
                            Time = new DateTime(2024, 6, 24, 9, 22, 37, 51, DateTimeKind.Local).AddTicks(4184)
                        },
                        new
                        {
                            AppointmentId = 6,
                            CompanyId = 4,
                            CustomerId = 2,
                            Time = new DateTime(2024, 7, 4, 9, 22, 37, 51, DateTimeKind.Local).AddTicks(4196)
                        },
                        new
                        {
                            AppointmentId = 7,
                            CompanyId = 5,
                            CustomerId = 5,
                            Time = new DateTime(2024, 5, 20, 9, 22, 37, 51, DateTimeKind.Local).AddTicks(4206)
                        },
                        new
                        {
                            AppointmentId = 8,
                            CompanyId = 5,
                            CustomerId = 6,
                            Time = new DateTime(2024, 5, 30, 9, 22, 37, 51, DateTimeKind.Local).AddTicks(4217)
                        },
                        new
                        {
                            AppointmentId = 9,
                            CompanyId = 6,
                            CustomerId = 5,
                            Time = new DateTime(2024, 6, 9, 9, 22, 37, 51, DateTimeKind.Local).AddTicks(4227)
                        },
                        new
                        {
                            AppointmentId = 10,
                            CompanyId = 6,
                            CustomerId = 6,
                            Time = new DateTime(2024, 6, 19, 9, 22, 37, 51, DateTimeKind.Local).AddTicks(4264)
                        },
                        new
                        {
                            AppointmentId = 11,
                            CompanyId = 1,
                            CustomerId = 7,
                            Time = new DateTime(2024, 5, 22, 9, 22, 37, 51, DateTimeKind.Local).AddTicks(4275)
                        },
                        new
                        {
                            AppointmentId = 12,
                            CompanyId = 2,
                            CustomerId = 8,
                            Time = new DateTime(2024, 5, 29, 9, 22, 37, 51, DateTimeKind.Local).AddTicks(4286)
                        },
                        new
                        {
                            AppointmentId = 13,
                            CompanyId = 3,
                            CustomerId = 9,
                            Time = new DateTime(2024, 6, 5, 9, 22, 37, 51, DateTimeKind.Local).AddTicks(4297)
                        },
                        new
                        {
                            AppointmentId = 14,
                            CompanyId = 4,
                            CustomerId = 10,
                            Time = new DateTime(2024, 6, 12, 9, 22, 37, 51, DateTimeKind.Local).AddTicks(4308)
                        },
                        new
                        {
                            AppointmentId = 15,
                            CompanyId = 5,
                            CustomerId = 7,
                            Time = new DateTime(2024, 6, 19, 9, 22, 37, 51, DateTimeKind.Local).AddTicks(4319)
                        },
                        new
                        {
                            AppointmentId = 16,
                            CompanyId = 6,
                            CustomerId = 8,
                            Time = new DateTime(2024, 6, 26, 9, 22, 37, 51, DateTimeKind.Local).AddTicks(4330)
                        },
                        new
                        {
                            AppointmentId = 17,
                            CompanyId = 1,
                            CustomerId = 9,
                            Time = new DateTime(2024, 7, 3, 9, 22, 37, 51, DateTimeKind.Local).AddTicks(4340)
                        },
                        new
                        {
                            AppointmentId = 18,
                            CompanyId = 2,
                            CustomerId = 10,
                            Time = new DateTime(2024, 7, 10, 9, 22, 37, 51, DateTimeKind.Local).AddTicks(4354)
                        });
                });

            modelBuilder.Entity("ProjectModels.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyId");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            CompanyId = 1,
                            Name = "Apple"
                        },
                        new
                        {
                            CompanyId = 2,
                            Name = "Samsung"
                        },
                        new
                        {
                            CompanyId = 3,
                            Name = "Xiaomi"
                        },
                        new
                        {
                            CompanyId = 4,
                            Name = "Google"
                        },
                        new
                        {
                            CompanyId = 5,
                            Name = "Microsoft"
                        },
                        new
                        {
                            CompanyId = 6,
                            Name = "Amazon"
                        });
                });

            modelBuilder.Entity("ProjectModels.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "Campusvägen 7",
                            FirstName = "Ermin",
                            LastName = "Husic",
                            PhoneNumber = 734141429
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "Storgatan 10",
                            FirstName = "Oskar",
                            LastName = "Johansson",
                            PhoneNumber = 723456789
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "Lilla vägen 3",
                            FirstName = "Sharam",
                            LastName = "Khan",
                            PhoneNumber = 734567890
                        },
                        new
                        {
                            CustomerId = 4,
                            Address = "Parkgatan 15",
                            FirstName = "Christian",
                            LastName = "Andersson",
                            PhoneNumber = 765432109
                        },
                        new
                        {
                            CustomerId = 5,
                            Address = "Skolgatan 2",
                            FirstName = "Lena",
                            LastName = "Eriksson",
                            PhoneNumber = 721567890
                        },
                        new
                        {
                            CustomerId = 6,
                            Address = "Kyrkvägen 6",
                            FirstName = "Andreas",
                            LastName = "Lindström",
                            PhoneNumber = 709876543
                        },
                        new
                        {
                            CustomerId = 7,
                            Address = "Strandvägen 12",
                            FirstName = "Emily",
                            LastName = "Nilsson",
                            PhoneNumber = 723456781
                        },
                        new
                        {
                            CustomerId = 8,
                            Address = "Backstugan 4",
                            FirstName = "David",
                            LastName = "Gustafsson",
                            PhoneNumber = 761234567
                        },
                        new
                        {
                            CustomerId = 9,
                            Address = "Musselvägen 4",
                            FirstName = "Sophia",
                            LastName = "Berg",
                            PhoneNumber = 723456782
                        },
                        new
                        {
                            CustomerId = 10,
                            Address = "Storgatan 2",
                            FirstName = "Alexander",
                            LastName = "Larsson",
                            PhoneNumber = 768765432
                        });
                });

            modelBuilder.Entity("ProjectModels.Appointment", b =>
                {
                    b.HasOne("ProjectModels.Company", "Company")
                        .WithMany("Appointments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectModels.Customer", "Customer")
                        .WithMany("Appointments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ProjectModels.Company", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("ProjectModels.Customer", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
